codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 40...80
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true
